# Site settings
title: The Ooze Is Loose
email: vnoronha@usc.edu
description: Infect enemies. Raise slimy monstrosities. Dominate the battlefield.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://theoozeisloose.github.io" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/theoozeisloose
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
