# Site settings
title: "C2: Creature Clash"
email: vnoronha@usc.edu
description: "Augemented Reality based creature card game."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://c2creatureclash.github.io" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/c2creatureclash
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
